services:
  php:
    container_name: afup-jeu-php
    build: .
    ports:
      - "${EXTERNAL_PORT:-80}:80"
    volumes:
      - ./data/composer:/var/www/.composer
      - ./.docker/sites-enabled/:/etc/apache2/sites-enabled/
      - ./:/var/www/html/
    links:
      - mysql
  mysql:
    container_name: afup-jeu-mysql
    image: mysql:5.7
    ports:
      - "${EXTERNAL_PORT_MYSQL:-3306}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jeu
